name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x' # Specify the Node.js version you want to use

      - name: Check for package.json
        run: test -f ./dags/package.json || echo "Error: package.json not found!" && exit 1

      - name: Install dependencies
        run: npm install
        working-directory: ./dags

      - name: Build static files
        run: npm run build
        working-directory: ./dags

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dags/build s3://hd-mwaa-bucket
